config/routes.rb
Rails.application.routes.draw do
  resources :usvideos
  get 'static_pages/home'
  get 'static_pages/help'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


root 'application#hello'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/usvideo.rb
class Usvideo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
protect_from_forgery with: :exception

def hello
    render html: "hello, world test!"
end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home

  end

  def help
  end
end

app/controllers/usvideos_controller.rb
class UsvideosController < ApplicationController
  before_action :set_usvideo, only: [:show, :edit, :update, :destroy]

  # GET /usvideos
  # GET /usvideos.json
  def index
    @usvideos = Usvideo.all
  end

  # GET /usvideos/1
  # GET /usvideos/1.json
  def show
  end

  # GET /usvideos/new
  def new
    @usvideo = Usvideo.new
  end

  # GET /usvideos/1/edit
  def edit
  end

  # POST /usvideos
  # POST /usvideos.json
  def create
    @usvideo = Usvideo.new(usvideo_params)

    respond_to do |format|
      if @usvideo.save
        format.html { redirect_to @usvideo, notice: 'Usvideo was successfully created.' }
        format.json { render :show, status: :created, location: @usvideo }
      else
        format.html { render :new }
        format.json { render json: @usvideo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usvideos/1
  # PATCH/PUT /usvideos/1.json
  def update
    respond_to do |format|
      if @usvideo.update(usvideo_params)
        format.html { redirect_to @usvideo, notice: 'Usvideo was successfully updated.' }
        format.json { render :show, status: :ok, location: @usvideo }
      else
        format.html { render :edit }
        format.json { render json: @usvideo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usvideos/1
  # DELETE /usvideos/1.json
  def destroy
    @usvideo.destroy
    respond_to do |format|
      format.html { redirect_to usvideos_url, notice: 'Usvideo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usvideo
      @usvideo = Usvideo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usvideo_params
      params.fetch(:usvideo, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/usvideos_helper.rb
module UsvideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LatestRubyProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<div class='container'>
  <div class="page-header">
    <h2>Ruby On Rails YouTube Search</h2>
  </div>

  <div class="row">
    <div class="input-group input-group-lg col-sm-8 col-md-8">
       <input type="text" class="form-control">
    </div>
  </div>

</div>

app/views/usvideos/_form.html.erb
<%= form_with(model: usvideo, local: true) do |form| %>
  <% if usvideo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(usvideo.errors.count, "error") %> prohibited this usvideo from being saved:</h2>

      <ul>
      <% usvideo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/usvideos/edit.html.erb
<h1>Editing Usvideo</h1>

<%= render 'form', usvideo: @usvideo %>

<%= link_to 'Show', @usvideo %> |
<%= link_to 'Back', usvideos_path %>

app/views/usvideos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Usvideos</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usvideos.each do |usvideo| %>
      <tr>
        <td><%= link_to 'Show', usvideo %></td>
        <td><%= link_to 'Edit', edit_usvideo_path(usvideo) %></td>
        <td><%= link_to 'Destroy', usvideo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usvideo', new_usvideo_path %>

app/views/usvideos/new.html.erb
<h1>New Usvideo</h1>

<%= render 'form', usvideo: @usvideo %>

<%= link_to 'Back', usvideos_path %>

app/views/usvideos/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_usvideo_path(@usvideo) %> |
<%= link_to 'Back', usvideos_path %>